<template>
  <div class="loader_conatiner" v-if="!isloaded">
    <div class="loadingio-spinner-rolling-fb60nmajg1f">
      <div class="ldio-a4qrqg6n4v5">
        <div>

        </div>
      </div>
    </div>
  </div>

</template>

<script>
export default {
  name: "preloader-item",
  data: () => {
    return {
      isloaded: false
    }
  },
  mounted() {
    document.onreadystatechange = () => {
      if(document.readyState === 'complete'){
        return this.isloaded = true
      }
    }
  }
}
</script>

<style scoped>
@keyframes ldio-a4qrqg6n4v5 {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.loader_conatiner{
  width: 100%;
  height: 100%;
  position: fixed;
  background-color: white;
  z-index: 999;
  display: flex;
  justify-content: center;
  align-items: center;
}
.ldio-a4qrqg6n4v5 div {
  position: absolute;
  width: 120px;
  height: 120px;
  border: 20px solid #4e64ea;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-a4qrqg6n4v5 div {
  animation: ldio-a4qrqg6n4v5 1s linear infinite;
  top: 100px;
  left: 100px
}
.loadingio-spinner-rolling-fb60nmajg1f {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: rgba(255, 255, 255, 0);
}
.ldio-a4qrqg6n4v5 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-a4qrqg6n4v5 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>